export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR';
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const CHANGE_VIEW_LIST = 'CHANGE_VIEW_LIST';